import type { ScanReport, SeverityCounts } from '../scanner/types';

/** Deterministic JSON export (stable key order via explicit shape). */
export function reportToJson(report: ScanReport): string {
  return JSON.stringify(report, null, 2);
}

/** CSV export of findings (spreadsheet-friendly). */
export function reportToCsv(report: ScanReport): string {
  const headers = ['Severity', 'Category', 'Rule ID', 'Title', 'File', 'Line', 'Evidence', 'Remediation'];
  const rows = report.findings.map((f) => [
    f.severity,
    f.category,
    f.ruleId,
    `"${f.title.replace(/"/g, '""')}"`,
    `"${f.file.replace(/"/g, '""')}"`,
    f.line ?? '',
    `"${f.evidence.replace(/"/g, '""')}"`,
    `"${f.remediation.replace(/"/g, '""')}"`,
  ]);
  return [headers, ...rows].map((row) => row.join(',')).join('\n');
}

/** XML export for tool integration. */
export function reportToXml(report: ScanReport): string {
  const escape = (str: string) => str.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c] || c));
  const lines: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<launchguard-report>',
    `  <project name="${escape(report.projectName)}" />`,
    `  <metadata>`,
    `    <score>${report.score}</score>`,
    `    <grade>${escape(report.grade)}</grade>`,
    `    <scannedAt>${report.scannedAt}</scannedAt>`,
    `    <fileCount>${report.fileCount}</fileCount>`,
    `  </metadata>`,
    `  <findings count="${report.findings.length}">`,
  ];
  for (const f of report.findings) {
    lines.push(`    <finding id="${escape(f.id)}">`);
    lines.push(`      <severity>${f.severity}</severity>`);
    lines.push(`      <category>${f.category}</category>`);
    lines.push(`      <ruleId>${f.ruleId}</ruleId>`);
    lines.push(`      <title>${escape(f.title)}</title>`);
    lines.push(`      <file>${escape(f.file)}</file>`);
    if (f.line) lines.push(`      <line>${f.line}</line>`);
    lines.push(`      <evidence>${escape(f.evidence)}</evidence>`);
    lines.push(`      <remediation>${escape(f.remediation)}</remediation>`);
    lines.push(`    </finding>`);
  }
  lines.push(`  </findings>`);
  lines.push('</launchguard-report>');
  return lines.join('\n');
}

const SEVERITY_LABELS: Array<[keyof SeverityCounts, string]> = [
  ['critical', 'Critical'],
  ['high', 'High'],
  ['medium', 'Medium'],
  ['low', 'Low'],
  ['info', 'Info'],
];

/** Human-readable Markdown export of a scan report. */
export function reportToMarkdown(report: ScanReport): string {
  const lines: string[] = [];
  lines.push(`# LaunchGuard report — ${report.projectName}`);
  lines.push('');
  lines.push(`- **Readiness score:** ${report.score}/100 (${report.grade})`);
  lines.push(`- **Source:** ${report.source.type} — ${report.source.ref}`);
  lines.push(`- **Scanned at:** ${report.scannedAt}`);
  lines.push(`- **Files scanned:** ${report.fileCount}${report.skippedFiles ? ` (${report.skippedFiles} skipped)` : ''}`);
  lines.push(`- **Rules evaluated:** ${report.rulesEvaluated}`);
  lines.push(`- **Scan duration:** ${report.durationMs} ms`);
  lines.push(`- **Fingerprint:** \`${report.fingerprint}\``);
  if (report.suppressedFindings > 0) {
    lines.push(`- **Suppressed findings:** ${report.suppressedFindings} (via launchguard.config.json)`);
  }
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('| --- | --- |');
  for (const [key, label] of SEVERITY_LABELS) {
    lines.push(`| ${label} | ${report.summary.bySeverity[key]} |`);
  }
  lines.push(`| **Total** | **${report.summary.total}** |`);
  lines.push('');

  if (Object.keys(report.summary.byCategory).length > 0) {
    lines.push('### By category');
    lines.push('');
    for (const [category, count] of Object.entries(report.summary.byCategory).sort()) {
      lines.push(`- ${category}: ${count}`);
    }
    lines.push('');
  }

  if (report.notes.length > 0) {
    lines.push('## Notes');
    lines.push('');
    for (const note of report.notes) lines.push(`- ${note}`);
    lines.push('');
  }

  lines.push('## Findings');
  lines.push('');
  if (report.findings.length === 0) {
    lines.push('No deployment risks were detected. 🎉');
  } else {
    for (const finding of report.findings) {
      lines.push(
        `### [${finding.severity.toUpperCase()}] ${finding.title} (${finding.ruleId})`
      );
      lines.push('');
      lines.push(`- **Category:** ${finding.category}`);
      lines.push(`- **File:** \`${finding.file}\`${finding.line ? ` (line ${finding.line})` : ''}`);
      lines.push(`- **Evidence:** ${finding.evidence}`);
      lines.push(`- **Remediation:** ${finding.remediation}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('_Generated by LaunchGuard. Secret-like values are redacted._');
  return lines.join('\n');
}

/** A safe file name stem derived from the project name. */
export function reportFileStem(report: ScanReport): string {
  const base = report.projectName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return `launchguard-${base || 'report'}`;
}
