import type { ScanReport, Severity } from '../scanner/types';
import { APP_NAME, APP_VERSION } from '../version';

/**
 * Standalone HTML report export: a single self-contained file (inline CSS,
 * no scripts, no external assets) that can be attached to a ticket, emailed
 * or printed. All dynamic text is HTML-escaped.
 */

const SEV_COLOR: Record<Severity, string> = {
  critical: '#f85149',
  high: '#db6d28',
  medium: '#d29922',
  low: '#58a6ff',
  info: '#8b949e',
};

function esc(value: string): string {
  return value.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] || c));
}

function scoreColorHex(score: number): string {
  if (score >= 90) return '#3fb950';
  if (score >= 75) return '#58a6ff';
  if (score >= 50) return '#d29922';
  if (score >= 25) return '#db6d28';
  return '#f85149';
}

export function reportToHtml(report: ScanReport): string {
  const rows = report.findings
    .map(
      (f) => `
      <tr>
        <td><span class="sev" style="background:${SEV_COLOR[f.severity]}1a;color:${SEV_COLOR[f.severity]};border-color:${SEV_COLOR[f.severity]}55">${esc(f.severity)}</span></td>
        <td>${esc(f.category)}</td>
        <td class="mono">${esc(f.ruleId)}</td>
        <td>
          <strong>${esc(f.title)}</strong>
          <div class="mono file">${esc(f.file)}${f.line ? `:${f.line}` : ''}</div>
          <div class="evidence">${esc(f.evidence)}</div>
          <div class="fix">Fix: ${esc(f.remediation)}</div>
        </td>
      </tr>`
    )
    .join('\n');

  const severitySummary = (Object.entries(report.summary.bySeverity) as Array<[Severity, number]>)
    .map(([sev, count]) => `<span class="pill" style="color:${SEV_COLOR[sev]}">${count} ${esc(sev)}</span>`)
    .join(' ');

  const notes = report.notes.length
    ? `<ul class="notes">${report.notes.map((n) => `<li>${esc(n)}</li>`).join('')}</ul>`
    : '';

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(APP_NAME)} report — ${esc(report.projectName)}</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 15px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif; margin: 0 auto; max-width: 960px; padding: 32px 20px 64px; color: #1f2328; background: #ffffff; }
  @media (prefers-color-scheme: dark) { body { color: #e6edf3; background: #0d1117; } th { background: #161b22; } }
  h1 { font-size: 1.5rem; margin: 0 0 4px; }
  .meta { color: #768390; font-size: 0.9rem; margin-bottom: 24px; }
  .scorebox { display: flex; align-items: center; gap: 18px; border: 1px solid #76839044; border-radius: 12px; padding: 18px 22px; margin: 18px 0; }
  .score { font-size: 2.6rem; font-weight: 700; }
  .grade { font-size: 1.05rem; color: #768390; }
  .pill { font-weight: 600; margin-right: 10px; }
  table { border-collapse: collapse; width: 100%; margin-top: 18px; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #76839033; vertical-align: top; }
  th { font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.04em; color: #768390; }
  .sev { display: inline-block; border: 1px solid; border-radius: 999px; padding: 1px 10px; font-size: 0.78rem; font-weight: 600; text-transform: uppercase; }
  .mono { font-family: ui-monospace, "Cascadia Code", Consolas, monospace; font-size: 0.85em; }
  .file { color: #768390; margin-top: 2px; }
  .evidence { margin-top: 6px; }
  .fix { margin-top: 4px; color: #768390; }
  .notes { color: #768390; font-size: 0.9rem; }
  footer { margin-top: 40px; color: #768390; font-size: 0.85rem; }
  @media print { body { padding: 0; } .scorebox { break-inside: avoid; } tr { break-inside: avoid; } }
</style>
</head>
<body>
<h1>${esc(APP_NAME)} report — ${esc(report.projectName)}</h1>
<div class="meta">
  Source: ${esc(report.source.type)} — ${esc(report.source.ref)} · Scanned ${esc(report.scannedAt)} ·
  ${report.fileCount} files · ${report.rulesEvaluated} rules · ${report.durationMs} ms · fingerprint <span class="mono">${esc(report.fingerprint)}</span>
</div>
<div class="scorebox">
  <div class="score" style="color:${scoreColorHex(report.score)}">${report.score}<span style="font-size:1rem;color:#768390">/100</span></div>
  <div>
    <div class="grade">${esc(report.grade)}</div>
    <div>${severitySummary}</div>
  </div>
</div>
${notes}
${
  report.findings.length === 0
    ? '<p>No deployment risks were detected. 🎉</p>'
    : `<table>
<thead><tr><th>Severity</th><th>Category</th><th>Rule</th><th>Finding</th></tr></thead>
<tbody>${rows}
</tbody></table>`
}
<footer>Generated by ${esc(APP_NAME)} v${esc(APP_VERSION)}. Secret-like values are redacted.</footer>
</body>
</html>`;
}
